### ISSUE TITLE
Don't store state moment in history if equal to previous state

### ISSUE THREAD

**Issue by funwithtriangles** [charkour/zundo#13]
Sometimes an action might happen in the store that results in no change to state. I can't see any reason to store these non-changes in history, as firing an undo will result in no changes.

**Comment by charkour** [comment]
Yup, totally makes sense. Thanks!

**Comment by nosferatu500** [comment]
I propose to do this as an option. Since in some cases I need the ability to save the state even if the state has not changed.

**Comment by nosferatu500** [comment]
For example: by default, save only if the state has changed. but provide the option to save the state even if there are no changes.

**Comment by nosferatu500** [comment]
For example, my project has 3 different components. In order to implement undo / redo for each component in the correct sequence, I created another one store in which I write in which component the change was made, so that I can later be able to undo/redo it. 

And in this case, I have 1 store in which I can have the same records in history. 
For example: [componentA -> componentA -> componentB -> componentC -> componentC]
And when the user will undo the state, I need to do it in the correct sequence for all components of the system, so it is important for me to be able to save the state even if no changes have been made.

I have 6 different stores and I need this feature only for 1 store. 

Because of this I propose to make ability to save the same state as an optional.

**Comment by charkour** [comment]
Thanks @nosferatu500, making it an option sounds like a great idea.

I'm curious why you need to track the order of updates to components? Would you be able to explain it further? I want to understand your use case.

**Comment by nosferatu500** [comment]
@charkour 

For example: 3 different canvas components (A, B, C)

User made changes in component A, then B, then drawing something again in B and again in C. When user will press Ctrl+Z s/he will await that state will be changed from C to A as C-> B->B->A.

For this purpose I created another one store and for each user's changes I made a record (name of component) which component was changed. (componentA -> componentB-> componentB-> componentC)

State each of this component is different but to make sure which component have to be "undo" I record name of each component in another store.

Therefore, the state of the latter can be repeated, and it is important to know in which of the above components I need to call undo.

**Comment by nosferatu500** [comment]
Or imagine Photoshop. When you change something like canvas, panel or some parameter and call undo later, it will do it exactly the same way you did it, but in reverse order. Because of this it's important to know right order for undo. And because of this name of component (canvas for example) can be the same for "undo/redo manager". All this time canvas will have a different state, but undo/redo manager know only name of which component was changed.

PS: I don't know how this works in Photoshop in real life. I mentioned this for example only.

**Comment by funwithtriangles** [comment]
Ah that's an interesting use case I hadn't thought of @nosferatu500. I hadn't considered multiple stores having to stay in sync. The question now is, what should the default be? I'd argue that the case of multiple stores is an edge case and for most purposes users would automatically want to skip over non-changes in history. However this would be a breaking change, so I understand why it might make sense to have it the other way around.

**Comment by charkour** [comment]
Released in [v1.2.1](https://www.npmjs.com/package/zundo/v/1.2.1)
